server:
  tomcat:
    accept-count: 1024
    max-connections: 8192
    threads:
      min-spare: 100
      max: 200

spring:
  application:
    name: Course-Registration-System

  web:
    resources:
      add-mappings: false

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DBNAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 600000
      keepalive-time: 60000
      auto-commit: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        criteria:
          literal_handling_mode: bind
        query:
          in_clause_parameter_padding: true
        connection:
          provider_disables_autocommit: true
    defer-datasource-initialization: true
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: caches, metrics


logging:
  level:
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR

springdoc:
  swagger-ui:
    display-request-duration: true
    operations-sorter: alpha
    try-it-out-enabled: true
    tags-sorter: alpha
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
