# RDB 설정
save 900 1
save 300 10
save 60 10000
dbfilename dump.rdb
rdbcompression yes
rdbchecksum yes
stop-writes-on-bgsave-error no


# AOF 설정
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
aof-load-truncated yes

# 데이터 디렉토리
dir /data

# 메모리 설정
maxmemory 512mb
maxmemory-policy allkeys-lru
